### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by eelmstrom** [eelmstrom/fish497#1]
*Created a remote repository for FISH497
*Created an R project
*Added folders for analysis and data
*Added a script for analysis and the raw data itself

**Comment by mdscheuerell** [comment]
Hint: if you want the bulleted list above to format nicely in Markdown, 1) put a space between the asterisk and the first letter, and 2) make sure there are at least 2 spaces after the last letter of a line.

So, for example, the following (where `<sp>` indicates a space)

```
* Created a remote repository for FISH497<sp><sp>
* Created an R project<sp><sp>
* Added folders for analysis and data<sp><sp>
* Added a script for analysis and the raw data itself<sp><sp>
```

will look like

* Created a remote repository for FISH497  
* Created an R project  
* Added folders for analysis and data  
* Added a script for analysis and the raw data itself

**Comment by mdscheuerell** [comment]
Nice job, Liz! (You can ignore my comment above—it was just an FYI.)

**Comment by eelmstrom** [comment]
Thanks Mark! The hint is helpful because that is what I was trying to do. :)

Hope you have a nice weekend. Yay for science!
Liz
